In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
a=np.array(55)
print(a)
print(a.ndim)
print(type(a))

55
0
<class 'numpy.ndarray'>


In [2]:
b=np.array([1,2,3,4])
print(b)
print(b.ndim)
print(type(b))

[1 2 3 4]
1
<class 'numpy.ndarray'>


In [3]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [4]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(d)
print(d.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
3


In [6]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(d)
print(d.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
3
